project:
  type: website
  output-dir: docs

website:
  title: "lazy planning programmer"
  navbar:
    right:
      - index.qmd
      - portfolio.qmd
      - about.qmd
      - icon: github
        href: https://github.com/Oh-Ji-Hoon

format:
  html:
    theme: Lux
    css: styles.css

editor: visual

